### ISSUE TITLE
Export / Report features by version

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/clevmetro-nfd#104]
We should allow people to be able downloading also different versions of the observation through the following REST endpoint:

Standard one:
http://test.nfd.geo-solutions.it/nfdapi/layers/plant/19/?format=csv

Versioned one:
http://test.nfd.geo-solutions.it/nfdapi/layers/plant/19/version/2?format=csv

**Comment by giohappy** [comment]
Both exports and report downloads must be by version.

**Comment by giohappy** [comment]
connect #106 
connect #90 
connect #145
