### ISSUE TITLE
Add a "print" button to download PDF

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/clevmetro-nfd#106]
Each feature and each version of a feature should have a print button allowing the users to download the PDF version of the observation sheet. Backend links to generate the PDFs for a single feature are:

 - http://test.nfd.geo-solutions.it/nfdapi/layers/animal/22/?format=pdf 

 - http://test.nfd.geo-solutions.it/nfdapi/layers/animal/22/version/1?format=pdf

connected to #104

**Comment by giohappy** [comment]
Follow the API as implemented by @ricardogsilva. See commit GH-134
