### ISSUE TITLE
Multiple selection for dictionary models

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/clevmetro-nfd#115]
Multiple selection must be provided for all dictionary tables **EXCEPT** the following tables:

4 (Canopy cover), 
6 (CM status), 
7 (Day time), 
12 (G-rank), 
17 (IUCN category), 
24 (Mushroom group), 
25 (N-rank), 
26 (occurrence category), 
27(plant count), 
28 (pond/lake type), 
33 (regional status), 
35 (s-rank), 
36 (season), 
43 (Stream designated use), 
46 (USFWS category), 
47 (Water flow type), 
49 (wetland connectivity), 
51 (wetland location)

**Comment by kappu72** [comment]
Size 1 also for forntend part

**Comment by giohappy** [comment]
??? what do yuo mean?
