### ISSUE TITLE
Move "Management" as last tab

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/clevmetro-nfd#121]
Move "Management" at the end of the tab list.

**Comment by ricardogsilva** [comment]
Apparently the last tab is actually for photographs and it is not set from the backend.
I can move the current _Management_ tab to the last position as mandated by the backend, but then it is up to the frontend to decide whether to put it before or after _Photographs_

**Comment by giohappy** [comment]
Move it before photographs

**Comment by ricardogsilva** [comment]
It is done in the pending PR
