### ISSUE TITLE
Observation position must be editable manually 

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/clevmetro-nfd#126]
Lat / lon fields should be exposed under "Location" to let the user edit coordinates manually.

This will require the API to serve the data for the frontend and accept locations in POST.

connected to #147

**Comment by kappu72** [comment]
I guess that the coords are stored in a geoserver layer and not in the db? If this is the case, we also need to update the coords in the geoserver layer.

**Comment by giohappy** [comment]
No, NFD doesn't have a geoserver layer. Only Django and PostGIS, so you and
Ricardo need to coordinate on this.

2018-02-07 10:50 GMT+01:00 Andrea <notifications@github.com>:

**Comment by giohappy** [comment]
Closed by PR 160
