### ISSUE TITLE
Reports (PDF) download menu by species

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/clevmetro-nfd#137]
Create e new button menu to list download links to the aggregated reports by species.

**Comment by kappu72** [comment]
I guess for species you mean feature type animal plant fungi slime/mold ... with featuresubtype as in add feature menu ?

**Comment by giohappy** [comment]
Yes, animal plant fungi slime/mold and natural areas. We will discuss
reports with them tomorrow, but I think a single aggregated report for
feature type will be enough.

2018-02-07 12:46 GMT+01:00 Andrea <notifications@github.com>:
