### ISSUE TITLE
Change filter fields in search window

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/clevmetro-nfd#139]
Remove the current fields from the filters..
The following fieldsets must be provided:

- Taxonomic ranks: **Order, family, genus**

- Location: **Reservation, Watershed**

- Rarity: **CM status** 

For Natural Areas only CM status (for the moment)

connected to #176

**Comment by kappu72** [comment]
For species we have a dedicate api search endpoint i.e. http://localhost:8081/nfdapi/species/?search=pi 
Is ti possible to search taxnomic ranks, location and rarity in the same way?

**Comment by giohappy** [comment]
I think yes. An additional param must be passed with the feature type (animal, etc.).
Probably a couple of additional fields will be required, I'm waiting NFD for the definitiva list

**Comment by giohappy** [comment]
closed by PR 203
