### ISSUE TITLE
LDAP Natural Areas groups and user_005 not mapped into NDF auth 

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/clevmetro-nfd#146]
naturalarea_writer and naturalarea_publisher groups are set in LDAP, but not available in Django.
The same for user_005.

We need to verify how the sync work and why these group and user are not synced correctly.
It's of the HIGHEST PRIORITY because we have to check Natural Areas, which are currently not available.

**Comment by ricardogsilva** [comment]
After checking the [GEOS 1 google drive doc](https://docs.google.com/document/d/1MkBsDpEu43r7YUrFcXRsM0oOAUg5hdtrlP_Tp2_pIRo/edit#) it seems there are actually two LDAP servers, one for **dev** and another for **test** (see page 8 of the document).

The user `user_005` existed on the **dev** server, but not on the **test** one.

The **test** LDAP server is the one that is configured in the settings of the app in http://test.nfd.geo-solutions.it/

So, using the installed _phpLDAPadmin_ app, I've created `user_005` on the test LDAP server and assigned it to the _naturalarea_writer_ group. This user is now able to login to the app.

It seems this solves the issue. Does it?

**Comment by giohappy** [comment]
It sounds great! I just tested login for user_005 and it works. So keep an eye on natural areas which has not been tested yet!
