### ISSUE TITLE
g_rank, s_rank and n_rank dropdowns items must include the rank code

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/clevmetro-nfd#148]
Currently the dropdowns show only the rank names, we must prefix it with the code.
E.g. (for G Rank):

"Globally unrankable" should become "GU - Globally unrankable".

(Note that the Django admin show them the correct way)

**IMPLEMENTATION DETAILS**: DictionaryTable models can have an additional configuration flag "show_key" that should be passed along the formitems configurations to the client. The client will use this flag to show or hide the code label. The n_rank, s_rank and g_rank subclasses can set it "true".

![ranks](https://user-images.githubusercontent.com/571129/35970859-2ecb4170-0ccc-11e8-9877-2c4bd4c93a5a.png)

**Comment by kappu72** [comment]
I double che the code and It's ok, It seems that client in test server is not updated.

**Comment by giohappy** [comment]
closed bt PR-170 and PR-171
