### ISSUE TITLE
Searches on ITIS Database and Species model refactoring

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/clevmetro-nfd#176]
The search functionality in the "Features" tab must do the following:

(WORKFLOW)

1. Search the typed text within ANY rank within the ITIS database for a certain kingdom (ITIS.taxonomic_units table).
2.  Any matching name will be suggested to the user with typeahead
3. When the user selects a name a new call to the backend will look for ALL the parent ranks (see recursive query example at the bottom)
4. The values from the parent ranks, along with other attributes from the taxonomic unit, will be used to populate the ranks fields.
5. Using the results from the previous point the django model instance will be saved.

IMPORTANT: every kingdom has its own ranks. I.e. ranks will be different for each kingdom (see ITIS.taxon_unit_types)
This means that each kingdom species needs its own set of ranks 
A solution can be to use a JSONField to store the ranks keys/values. 
This field will be looked up to implement the "filter search by taxonomic ranks" ( see #139 )

I see the following steps.

(SUBTASKS)

1. Import relevant ITIS database tables inside  the NFD database (taxonomic_units and taxon_unit_types as a minimum). 
2. Change the search endpoint to look for ANY value inside taxonomic_units.unit_name1, using a LIKE lookup. I would keep this simple, without considering vernacular terms, translations, etc.
The search must be done by Kingdom, so the client must provide the kingdom to search for dependeing on the feature type being edited.
We must ensure that the searched field has an index for it!
3. Return any result to the client. It can be any value from any rank.
4. Implement the endpoint for point 5 of the WORKFLOW. A recursive query can be used on the taxonomic_units (see below). It will return the ranks values to the client.
5. Change the feature save/update to store the the ranks values inside the JSONField.

Example for recursive query:

`
WITH RECURSIVE parent_ranks(tsn, parent_tsn, kingdom_id, rank_id, r_depth) AS (
 SELECT
 u.tsn, u.parent_tsn, u.kingdom_id, u.rank_id, 1
 FROM
 taxonomic_units u
 WHERE
 u.tsn = 65
 UNION
 SELECT
 u2.tsn, u2.parent_tsn, u2.kingdom_id, u2.rank_id, pr.r_depth + 1
 FROM
 taxonomic_units u2, parent_ranks pr
 WHERE u2.tsn = pr.parent_tsn
) SELECT
 distinct tsn, parent_tsn, kingdom_id, rank_id
FROM
 parent_ranks
 order by rank_id
`

**Comment by ricardogsilva** [comment]
Some comments on the proposed subtasks:

1. Perhaps we can work with the ITIS DB side-by-side with our DB and not import anything. We can add new settings with the connection parameters to ITIS;
1. So we'll need to add indexes to the relevant table columns. This means that if we keep ITIS DB side-by-side, thre will need to be some sort of `prepare_itis_db` script to create these indexes

**Comment by giohappy** [comment]
I agree, we can keep side-by-side. I was thinking the same this evening.
If it will be faster we can also use raw psycopg connections with plain SQL to query it...

**Comment by ricardogsilva** [comment]
The #188 PR will solve most of this issue.
However, there is still some work to do on the frontend on the search of existing Taxa.

Previously all the species were pre-imported into our DB so the search endpoint was always the same.
Now the frontend needs to use two different search endpoints:

- `/nfdapi/taxon_search` - This endpoint is used on the featuretype forms when the user is creating a new occurrence. It searches both the Taxon instances that have already been created and the ITIS database;
- `nfdapi/taxon` - This endpoint should be used on the _Search Categories_ section of the frontend, for when the user is searching through the taxa that have already been registered on the local DB.

**Comment by giohappy** [comment]
@ricardogsilva @kappu72 

`taxon_search` should be called with the feature type. The backend should filter the search on the kingdom depending on the feature type:

- Animals -> Animalia
- Plants -> Plantae
- Fungi and Slime molds -> Fungi

I see that "kingdoms" paramseter is accepted from the taxon_search request, but I would move the mapping on the server. The client should pass the featuretype in the request.

**Comment by giohappy** [comment]
Fixed in various PRs....
