### ISSUE TITLE
Internal server error on /list endpoint

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/clevmetro-nfd#191]
An internal server error appears now. It happens only for the feature types where the user has permissions. For example it happens with plants and animals for user_004, while the error doesn't raise when the endpoint is called for fungi or slime molds.

![image](https://user-images.githubusercontent.com/571129/36724425-716fff8e-1bb3-11e8-840c-a7f6615ba9bc.png)

**Comment by ricardogsilva** [comment]
This error seems to be due to an incomplete deployment. With the new `models.Taxon` model replacing the previous `models.Species` we need to update the pre-existing `Occurrence` objects manually

**Comment by giohappy** [comment]
Fixed by db records update
