### ISSUE TITLE
Search typeahead wrong "cache hits"

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/clevmetro-nfd#215]
Typeahead sends requests only the first time a list of chars are typed, and this gives the following problems:

1) user types "p" -> the request to the server starts
2) user types "pi" -> the old request is discarded
3) the user goes back to "p" -> **"NO MATCHED FOUND" and no new request is triggered**

**Comment by kappu72** [comment]
To search tow characters are needed.

**Comment by giohappy** [comment]
thought it was related to #213. I'll close it then
