### ISSUE TITLE
Missing User feedback when saving a feature without filling the required fields.   

### ISSUE THREAD

**Issue by fouad-semaan** [geosolutions-it/clevmetro-nfd#240]
![image](https://user-images.githubusercontent.com/38422316/40366146-b8bb5720-5dd6-11e8-950c-8a1ed20b0686.png)

**Comment by kappu72** [comment]
Backend regressions in error notification. The backend is no more sending the info about the errors.

**Comment by giohappy** [comment]
@ricardogsilva this is for you...
