### ISSUE TITLE
Increase photo upload limit

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/clevmetro-nfd#268]
We should set a higher limit because photos from mobiles can be quite large, and the user can upload multiple photos.
Maybe a 50MB limit could work.

**Comment by ricardogsilva** [comment]
I've spent some time on this and could not find a definitive solution yet. The situation is as follows:

-  The nfdclient UI claims that the maximum upload size is 5MB 
-  However, the python server app does not seem to be limiting the upload size in any way
-  On my local dev environment, I can upload pictures larger than 5 MB without problem. This is using the django test server
-  On the test server I can also upload pictures larger than 5 MB, but the situation is strange:
   -  In all cases the image thumbnail is correctly generated and is accessible
   -  If image is smaller than a certain size (presumably 5MB), it is uploaded with correct permissions and can be served by the backend
   - If image is bigger than said size, the upload still works OK, but the file permissions are incorrectly set, thus making the image impossible to serve

**Comment by giohappy** [comment]
Something wrong in the code that saves the thumbnail? https://github.com/geosolutions-it/clevmetro-nfd/blob/master/nfdapi/nfdcore/models.py#L171

**Comment by giohappy** [comment]
Maybe  forse file permissions with https://docs.djangoproject.com/en/2.0/ref/settings/#file-upload-permissions ?

**Comment by giohappy** [comment]
This answer seems to confirm my proposal (set FILE_UPLOAD_PERMISSIONS):
https://stackoverflow.com/a/38673672

**Comment by ricardogsilva** [comment]
After setting `FILE_UPLOAD_PERMISSIONS = 0644` I have successfully uploaded a 15 MB picture to the test server. I'll push a small PR with the change to sole the issue
